// Relationship types
export const RELATIONSHIP_TYPES = {
  LOSES_TO: "LOSES_TO",
  HAS_WEAKNESS: "HAS_WEAKNESS",
  HAS_STRENGTH: "HAS_STRENGTH",
  DECISION_DRIVER: "DECISION_DRIVER",
  BOUGHT: "BOUGHT",
  INVOLVES: "INVOLVES",
  MENTIONS: "MENTIONS",
  BELONGS_TO: "BELONGS_TO"
};
